# Generated by Django 4.1.6 on 2023-02-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_of_arrival',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time_of_departure',
            field=models.DateTimeField(),
        ),
    ]
