# Generated by Django 4.1.6 on 2023-02-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tripcost_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripcost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripcost',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
