# Generated by Django 4.1.6 on 2023-02-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trip_time_of_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('A', 'Arrived'), ('O', 'Ongoing')], default='O', max_length=1),
        ),
    ]
