# Generated by Django 4.1.6 on 2023-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin',
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.CharField(choices=[('K-L', 'kano - Lagos'), ('L-K', 'Lagos - Kano')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
