# Generated by Django 4.1.6 on 2023-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_trip_destination_remove_trip_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Idle'), ('M', 'Maintainance')], default='I', max_length=1),
        ),
    ]
