# Generated by Django 4.1.6 on 2023-02-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_truck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.truck'),
        ),
    ]
