# Generated by Django 4.1.6 on 2023-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_trip_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='unique_identifier',
            field=models.CharField(default='something', max_length=10),
            preserve_default=False,
        ),
    ]
