# Generated by Django 4.1.6 on 2023-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_truck_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_of_trip',
            field=models.DateField(blank=True, null=True),
        ),
    ]
