# Generated by Django 4.1.6 on 2023-02-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_trip_date_of_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time_of_departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
