# Generated by Django 4.1.6 on 2023-02-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_trip_time_of_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='diesel_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='load_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
